using BillingBackend.Data;
using BillingBackend.Extensions;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using System;
using System.IO;

namespace BillingBackend.Migrator
{
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("==================================================");
            Console.WriteLine("Starting SmartBilling Database Migrator...");
            Console.WriteLine("==================================================");

            // 1. Build Configuration
            var configuration = new ConfigurationBuilder()
                .SetBasePath(AppDomain.CurrentDomain.BaseDirectory)
                .AddJsonFile("appsettings.json", optional: true)
                // Search in project root and parent directories
                .AddJsonFile(Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "..", "..", "..", "BillingBackend", "appsettings.json"), optional: true)
                .AddJsonFile(Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "..", "..", "..", "..", "BillingBackend", "appsettings.json"), optional: true)
                .AddEnvironmentVariables()
                .Build();

            var connectionString = configuration.GetConnectionString("DefaultConnection");
            if (string.IsNullOrEmpty(connectionString))
            {
                Console.ForegroundColor = ConsoleColor.Red;
                Console.WriteLine("Error: DefaultConnection string is missing from configuration.");
                Console.ResetColor();
                return;
            }

            Console.WriteLine($"Using Connection String: {connectionString}");

            // 2. Register Database via BillingBackend's exact AddDatabase extension method
            var services = new ServiceCollection();
            services.AddDatabase(configuration);

            var serviceProvider = services.BuildServiceProvider();

            using (var scope = serviceProvider.CreateScope())
            {
                var context = scope.ServiceProvider.GetRequiredService<BillingDbContext>();
                try
                {
                    Console.WriteLine("\n[1/2] Applying latest schema alters (columns, constraints, and new tables)...");

                    // Explicitly create the new WhatsApp integration tables if they don't exist
                    ExecuteAlter(context, @"
                        CREATE TABLE ""WhatsAppAccounts"" (
                            ""Id"" NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                            ""BusinessId"" NUMBER(10) NOT NULL,
                            ""MetaBusinessId"" VARCHAR2(100),
                            ""WabaId"" VARCHAR2(100),
                            ""PhoneNumberId"" VARCHAR2(100),
                            ""DisplayPhoneNumber"" VARCHAR2(30),
                            ""AccessToken"" VARCHAR2(1000),
                            ""TokenExpiry"" TIMESTAMP,
                            ""Status"" VARCHAR2(20) NOT NULL,
                            ""ConnectedAt"" TIMESTAMP NOT NULL,
                            ""DisconnectedAt"" TIMESTAMP,
                            CONSTRAINT ""FK_WA_Business"" FOREIGN KEY (""BusinessId"") REFERENCES ""Businesses""(""Id"") ON DELETE CASCADE
                        )");

                    ExecuteAlter(context, @"
                        CREATE TABLE ""MessageLogs"" (
                            ""Id"" NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                            ""WhatsAppAccountId"" NUMBER(10) NOT NULL,
                            ""BillId"" NUMBER(10),
                            ""RecipientPhone"" VARCHAR2(20) NOT NULL,
                            ""MessageType"" VARCHAR2(20) NOT NULL,
                            ""MetaMessageId"" VARCHAR2(200),
                            ""Status"" VARCHAR2(20) NOT NULL,
                            ""SentAt"" TIMESTAMP NOT NULL,
                            ""DeliveredAt"" TIMESTAMP,
                            ""ReadAt"" TIMESTAMP,
                            ""FailedReason"" VARCHAR2(500),
                            CONSTRAINT ""FK_MsgLog_WA"" FOREIGN KEY (""WhatsAppAccountId"") REFERENCES ""WhatsAppAccounts""(""Id"") ON DELETE CASCADE,
                            CONSTRAINT ""FK_MsgLog_Bill"" FOREIGN KEY (""BillId"") REFERENCES ""Bills""(""Id"") ON DELETE SET NULL
                        )");

                    // General schema alters
                    ExecuteAlter(context, "ALTER TABLE \"StaffMembers\" DROP CONSTRAINT \"FK_Staff_Branches_BranchId\"");
                    ExecuteAlter(context, "ALTER TABLE \"StaffMembers\" DROP COLUMN \"BranchId\"");
                    ExecuteAlter(context, "ALTER TABLE \"Users\" ADD \"PasswordResetToken\" VARCHAR2(100) NULL");
                    ExecuteAlter(context, "ALTER TABLE \"Users\" ADD \"PasswordResetTokenExpiry\" TIMESTAMP NULL");
                    ExecuteAlter(context, "ALTER TABLE \"Categories\" ADD \"ParentId\" NUMBER(10) NULL");
                    ExecuteAlter(context, "ALTER TABLE \"Services\" ADD \"ImageUrl\" VARCHAR2(500) NULL");
                    ExecuteAlter(context, "ALTER TABLE \"InventoryItems\" ADD \"ImageUrl\" VARCHAR2(500) NULL");
                    ExecuteAlter(context, "ALTER TABLE \"Businesses\" ADD \"IsSuspended\" NUMBER(1) DEFAULT 0 NOT NULL");

                    // WhatsApp Cloud API Integration Migration
                    // Drop old WhatsApp tables (templates first due to FK, then settings)
                    ExecuteAlter(context, "DROP TABLE \"WhatsAppTemplates\"");
                    ExecuteAlter(context, "DROP TABLE \"WhatsAppSettings\"");

                    // Add InvoicePdfUrl column to Bills table
                    ExecuteAlter(context, "ALTER TABLE \"Bills\" ADD \"InvoicePdfUrl\" VARCHAR2(500) NULL");

                    // Add UserRefreshTokens table
                    ExecuteAlter(context, @"
                        CREATE TABLE ""UserRefreshTokens"" (
                            ""Id"" NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                            ""UserId"" NUMBER(10) NOT NULL,
                            ""Token"" VARCHAR2(500) NOT NULL,
                            ""ExpiryTime"" TIMESTAMP NOT NULL,
                            ""IsRevoked"" NUMBER(1) DEFAULT 0 NOT NULL,
                            ""CreatedAt"" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
                            CONSTRAINT ""FK_RefreshToken_User"" FOREIGN KEY (""UserId"") REFERENCES ""Users""(""Id"") ON DELETE CASCADE
                        )");

                    // Add index on Token
                    ExecuteAlter(context, @"
                        CREATE UNIQUE INDEX ""IX_UserRefreshTokens_Token"" ON ""UserRefreshTokens""(""Token"")");

                    // ===== Subscription & Razorpay Integration Tables =====
                    ExecuteAlter(context, @"
                        CREATE TABLE ""SubscriptionPlans"" (
                            ""Id"" NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                            ""Name"" VARCHAR2(100) NOT NULL,
                            ""RazorpayPlanIdMonthly"" VARCHAR2(100) NOT NULL,
                            ""RazorpayPlanIdYearly"" VARCHAR2(100) NOT NULL,
                            ""MonthlyPrice"" NUMBER(18,2) NOT NULL,
                            ""YearlyPrice"" NUMBER(18,2) NOT NULL,
                            ""MaxBranches"" NUMBER(10) NOT NULL,
                            ""MaxStaff"" NUMBER(10) NOT NULL,
                            ""IsActive"" NUMBER(1) DEFAULT 1 NOT NULL
                        )");

                    ExecuteAlter(context, @"
                        CREATE TABLE ""PendingRegistrations"" (
                            ""Id"" NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                            ""Token"" VARCHAR2(100) NOT NULL,
                            ""Email"" VARCHAR2(256) NOT NULL,
                            ""Username"" VARCHAR2(100) NOT NULL,
                            ""PasswordHash"" BLOB NOT NULL,
                            ""PasswordSalt"" BLOB NOT NULL,
                            ""LegalName"" VARCHAR2(200) NOT NULL,
                            ""Phone"" VARCHAR2(20) NULL,
                            ""GstIn"" VARCHAR2(50) NULL,
                            ""Address"" VARCHAR2(500) NULL,
                            ""SelectedPlanId"" NUMBER(10) NOT NULL,
                            ""RazorpayCustomerId"" VARCHAR2(100) NULL,
                            ""RazorpaySubscriptionId"" VARCHAR2(100) NULL,
                            ""Status"" VARCHAR2(50) DEFAULT 'PendingPayment' NOT NULL,
                            ""ReminderEmailSent"" NUMBER(1) DEFAULT 0 NOT NULL,
                            ""ReminderEmailSentAt"" TIMESTAMP NULL,
                            ""CreatedAt"" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
                            ""ExpiresAt"" TIMESTAMP NOT NULL,
                            ""RawRegistrationData"" NCLOB NULL
                        )");

                    ExecuteAlter(context, @"
                        CREATE UNIQUE INDEX ""IX_PendingReg_Token"" ON ""PendingRegistrations""(""Token"")");

                    ExecuteAlter(context, @"
                        CREATE INDEX ""IX_PendingReg_Email"" ON ""PendingRegistrations""(""Email"")");

                    ExecuteAlter(context, @"
                        CREATE TABLE ""PaymentTransactions"" (
                            ""Id"" NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                            ""BusinessId"" NUMBER(10) NULL,
                            ""RazorpayPaymentId"" VARCHAR2(100) NULL,
                            ""RazorpayOrderId"" VARCHAR2(100) NULL,
                            ""RazorpaySubscriptionId"" VARCHAR2(100) NULL,
                            ""Amount"" NUMBER(18,2) NOT NULL,
                            ""Status"" VARCHAR2(50) NOT NULL,
                            ""PaymentMethod"" VARCHAR2(50) NULL,
                            ""RawWebhookPayload"" NCLOB NULL,
                            ""CreatedAt"" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
                        )");

                    // Alter Businesses table to add subscription columns
                    ExecuteAlter(context, @"ALTER TABLE ""Businesses"" ADD ""ActivePlanId"" NUMBER(10) DEFAULT 1 NOT NULL");
                    ExecuteAlter(context, @"ALTER TABLE ""Businesses"" ADD ""AllowedBranches"" NUMBER(10) DEFAULT 1 NOT NULL");
                    ExecuteAlter(context, @"ALTER TABLE ""Businesses"" ADD ""RazorpayCustomerId"" VARCHAR2(100) NULL");
                    ExecuteAlter(context, @"ALTER TABLE ""Businesses"" ADD ""RazorpaySubscriptionId"" VARCHAR2(100) NULL");
                    ExecuteAlter(context, @"ALTER TABLE ""Businesses"" ADD ""SubscriptionStatus"" VARCHAR2(50) DEFAULT 'Inactive' NOT NULL");
                    ExecuteAlter(context, @"ALTER TABLE ""Businesses"" ADD ""SubscriptionExpiresAt"" TIMESTAMP NULL");

                    try
                    {
                        ExecuteAlter(context, @"ALTER TABLE ""PendingRegistrations"" ADD ""RawRegistrationData"" NCLOB NULL");
                    }
                    catch (Exception) { /* Column might already exist */ }

                    // Custom Branch & Staff updates
                    try { ExecuteAlter(context, @"ALTER TABLE ""Businesses"" ADD ""AllowedStaff"" NUMBER(10) DEFAULT 2 NOT NULL"); } catch(Exception){}
                    try { ExecuteAlter(context, @"ALTER TABLE ""StaffMembers"" ADD ""BranchId"" NUMBER(10) NULL"); } catch(Exception){}
                    try { ExecuteAlter(context, @"ALTER TABLE ""StaffMembers"" ADD CONSTRAINT FK_StaffMembers_Branches FOREIGN KEY (""BranchId"") REFERENCES ""Branches""(""Id"") ON DELETE SET NULL"); } catch(Exception){}
                    try { ExecuteAlter(context, @"CREATE INDEX ""IX_StaffMembers_BranchId"" ON ""StaffMembers""(""BranchId"")"); } catch(Exception){}
                    try { ExecuteAlter(context, @"ALTER TABLE ""PaymentTransactions"" ADD ""WebhookEventId"" NUMBER(10) NULL"); } catch(Exception){}
                    try { ExecuteAlter(context, @"ALTER TABLE ""PaymentTransactions"" ADD ""UpdatedAt"" TIMESTAMP NULL"); } catch(Exception){}
                    try { ExecuteAlter(context, @"ALTER TABLE ""PaymentTransactions"" ADD ""FailureReason"" VARCHAR2(500) NULL"); } catch(Exception){}
                    try { ExecuteAlter(context, @"ALTER TABLE ""PaymentTransactions"" ADD ""RetryCount"" NUMBER(10) DEFAULT 0 NOT NULL"); } catch(Exception){}
                    try { ExecuteAlter(context, @"ALTER TABLE ""PaymentTransactions"" ADD ""CorrelationId"" VARCHAR2(100) NULL"); } catch(Exception){}
                    try { ExecuteAlter(context, @"ALTER TABLE ""Businesses"" ADD ""UpdatedAt"" TIMESTAMP NULL"); } catch(Exception){}
                    try { ExecuteAlter(context, @"ALTER TABLE ""StaffMembers"" ADD ""UpdatedAt"" TIMESTAMP NULL"); } catch(Exception){}
                    try { ExecuteAlter(context, @"ALTER TABLE ""Services"" ADD ""UpdatedAt"" TIMESTAMP NULL"); } catch(Exception){}
                    try { ExecuteAlter(context, @"ALTER TABLE ""InventoryItems"" ADD ""UpdatedAt"" TIMESTAMP NULL"); } catch(Exception){}
                    try { ExecuteAlter(context, @"ALTER TABLE ""Customers"" ADD ""UpdatedAt"" TIMESTAMP NULL"); } catch(Exception){}
                    try { ExecuteAlter(context, @"ALTER TABLE ""Bills"" ADD ""UpdatedAt"" TIMESTAMP NULL"); } catch(Exception){}
                    try { ExecuteAlter(context, @"ALTER TABLE ""Bills"" ADD ""PaymentReference"" VARCHAR2(200) NULL"); } catch(Exception){}
                    try { ExecuteAlter(context, @"ALTER TABLE ""Bills"" ADD ""IdempotencyKey"" VARCHAR2(100) NULL"); } catch(Exception){}
                    try { ExecuteAlter(context, @"ALTER TABLE ""Bills"" ADD ""Notes"" VARCHAR2(500) NULL"); } catch(Exception){}

                    // AuditLogs Table
                    ExecuteAlter(context, @"
                        CREATE TABLE ""AuditLogs"" (
                            ""Id"" NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                            ""BusinessId"" NUMBER(10) NULL,
                            ""EntityType"" VARCHAR2(50) NOT NULL,
                            ""EntityId"" NUMBER(10) NULL,
                            ""Action"" VARCHAR2(50) NOT NULL,
                            ""OldValues"" NCLOB NULL,
                            ""NewValues"" NCLOB NULL,
                            ""PerformedBy"" VARCHAR2(100) NULL,
                            ""IpAddress"" VARCHAR2(50) NULL,
                            ""UserAgent"" VARCHAR2(500) NULL,
                            ""CorrelationId"" VARCHAR2(100) NULL,
                            ""Description"" VARCHAR2(1000) NULL,
                            ""CreatedAt"" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
                        )");

                    // WebhookEventLogs Table
                    ExecuteAlter(context, @"
                        CREATE TABLE ""WebhookEventLogs"" (
                            ""Id"" NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                            ""Source"" VARCHAR2(50) NOT NULL,
                            ""ExternalEventId"" VARCHAR2(200) NULL,
                            ""EventType"" VARCHAR2(100) NOT NULL,
                            ""RawPayload"" NCLOB NULL,
                            ""ProcessingStatus"" VARCHAR2(30) DEFAULT 'Received' NOT NULL,
                            ""FailureReason"" VARCHAR2(2000) NULL,
                            ""RetryCount"" NUMBER(10) DEFAULT 0 NOT NULL,
                            ""CreatedAt"" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
                            ""ProcessedAt"" TIMESTAMP NULL
                        )");

                    // Seeding SuperAdmin User dynamically
                    try
                    {
                        var hasAdmin = context.Users.Any(u => u.Role == "SuperAdmin");
                        if (!hasAdmin)
                        {
                            using (var hmac = new System.Security.Cryptography.HMACSHA512())
                            {
                                var passwordHash = hmac.ComputeHash(System.Text.Encoding.UTF8.GetBytes("adminpassword123"));
                                var passwordSalt = hmac.Key;

                                var adminUser = new BillingBackend.Data.Entities.User
                                {
                                    Username = "superadmin",
                                    Email = "admin@smartbill.pro",
                                    PasswordHash = passwordHash,
                                    PasswordSalt = passwordSalt,
                                    Role = "SuperAdmin"
                                };
                                context.Users.Add(adminUser);
                                context.SaveChanges();
                                Console.ForegroundColor = ConsoleColor.Green;
                                Console.WriteLine("\n[Seeded] Default SuperAdmin created: username='superadmin', password='adminpassword123', email='admin@smartbill.pro'");
                                Console.ResetColor();
                            }
                        }
                    }
                    catch (Exception ex)
                    {
                        Console.WriteLine($"[Seeding Skipped - Table Lock or Exists] {ex.Message}");
                    }
                    Console.ForegroundColor = ConsoleColor.Green;
                    Console.WriteLine("\nDatabase Migrator finished execution successfully!");
                    Console.ResetColor();
                }
                catch (Exception ex)
                {
                    Console.ForegroundColor = ConsoleColor.Red;
                    Console.WriteLine($"\nMigration Failed: {ex.Message}");
                    if (ex.InnerException != null)
                    {
                        Console.WriteLine($"Inner Exception: {ex.InnerException.Message}");
                    }
                    Console.ResetColor();
                }
            }
        }

        static void ExecuteAlter(BillingDbContext context, string sql)
        {
            try
            {
                context.Database.ExecuteSqlRaw(sql);
                Console.WriteLine($"[Applied] {sql}");
            }
            catch (Exception)
            {
                // Most alters fail if the column or constraint is already modified/present. This is normal.
                Console.WriteLine($"[Skipped - Already Applied] {sql}");
            }
        }
    }
}
