using System;
using System.IO;
using System.Linq;
using BillingBackend.Data;
using BillingBackend.Data.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;

namespace BillingBackend.Migrator
{
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("==================================================");
            Console.WriteLine("SmartBilling Local Oracle DB Fresh Setup & Purge");
            Console.WriteLine("Target: SYSTEM / admin123 @ localhost:1521/XEPDB1");
            Console.WriteLine("==================================================");

            var connectionString = "User Id=SYSTEM;Password=admin123;Data Source=localhost:1521/XEPDB1;";

            var services = new ServiceCollection();
            services.AddDbContext<BillingDbContext>(options =>
                options.UseOracle(connectionString));

            var serviceProvider = services.BuildServiceProvider();

            bool dropOnly = args.Contains("--drop-only") || args.Contains("drop");

            using (var scope = serviceProvider.CreateScope())
            {
                var context = scope.ServiceProvider.GetRequiredService<BillingDbContext>();
                try
                {
                    Console.WriteLine("\n[1/3] Purging all Oracle tables, views, sequences, synonyms & recyclebin...");
                    context.Database.ExecuteSqlRaw(@"
                        BEGIN
                            FOR pass IN 1..5 LOOP
                                FOR t IN (SELECT table_name FROM user_tables) LOOP
                                    BEGIN
                                        EXECUTE IMMEDIATE 'DROP TABLE ""' || t.table_name || '"" CASCADE CONSTRAINTS PURGE';
                                    EXCEPTION WHEN OTHERS THEN NULL;
                                    END;
                                END LOOP;
                            END LOOP;
                            FOR s IN (SELECT sequence_name FROM user_sequences) LOOP
                                BEGIN
                                    EXECUTE IMMEDIATE 'DROP SEQUENCE ""' || s.sequence_name || '""';
                                EXCEPTION WHEN OTHERS THEN NULL;
                                END;
                            END LOOP;
                            FOR v IN (SELECT view_name FROM user_views) LOOP
                                BEGIN
                                    EXECUTE IMMEDIATE 'DROP VIEW ""' || v.view_name || '"" CASCADE CONSTRAINTS';
                                EXCEPTION WHEN OTHERS THEN NULL;
                                END;
                            END LOOP;
                            FOR syn IN (SELECT synonym_name FROM user_synonyms) LOOP
                                BEGIN
                                    EXECUTE IMMEDIATE 'DROP SYNONYM ' || syn.synonym_name;
                                EXCEPTION WHEN OTHERS THEN NULL;
                                END;
                            END LOOP;
                            BEGIN
                                EXECUTE IMMEDIATE 'PURGE RECYCLEBIN';
                            EXCEPTION WHEN OTHERS THEN NULL;
                            END;
                        END;");
                    Console.WriteLine("✓ Purged all Oracle tables, sequences, views, synonyms, and recyclebin cleanly.");

                    if (dropOnly)
                    {
                        Console.WriteLine("\n==================================================");
                        Console.WriteLine("SUCCESS: All Oracle database tables completely purged!");
                        Console.WriteLine("==================================================");
                        return;
                    }

                    Console.WriteLine("\n[2/3] Creating 26 fresh Oracle Database schema tables...");
                    string[] createTableSqls = new[]
                    {
                        @"CREATE TABLE ""Users"" (
                            ""Id"" NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                            ""Username"" VARCHAR2(100) NOT NULL UNIQUE,
                            ""Email"" VARCHAR2(256) NOT NULL UNIQUE,
                            ""PasswordHash"" RAW(2000) NOT NULL,
                            ""PasswordSalt"" RAW(2000) NOT NULL,
                            ""Role"" VARCHAR2(50) DEFAULT 'Owner' NOT NULL,
                            ""PasswordResetToken"" VARCHAR2(100),
                            ""PasswordResetTokenExpiry"" TIMESTAMP,
                            ""CreatedAt"" TIMESTAMP NOT NULL
                        )",

                        @"CREATE TABLE ""SubscriptionPlans"" (
                            ""Id"" NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                            ""Name"" VARCHAR2(100) NOT NULL,
                            ""RazorpayPlanIdMonthly"" VARCHAR2(100) NOT NULL,
                            ""RazorpayPlanIdYearly"" VARCHAR2(100) NOT NULL,
                            ""MonthlyPrice"" NUMBER(18,2) NOT NULL,
                            ""YearlyPrice"" NUMBER(18,2) NOT NULL,
                            ""MaxBranches"" NUMBER(10) NOT NULL,
                            ""MaxStaff"" NUMBER(10) NOT NULL,
                            ""IsActive"" NUMBER(1) DEFAULT 1 NOT NULL
                        )",

                        @"CREATE TABLE ""Businesses"" (
                            ""Id"" NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                            ""OwnerId"" NUMBER(10) NOT NULL UNIQUE REFERENCES ""Users""(""Id"") ON DELETE CASCADE,
                            ""LegalName"" VARCHAR2(200) NOT NULL,
                            ""TradingName"" VARCHAR2(200),
                            ""LogoUrl"" VARCHAR2(500),
                            ""Address"" VARCHAR2(500),
                            ""City"" VARCHAR2(100),
                            ""State"" VARCHAR2(100),
                            ""PostalCode"" VARCHAR2(20),
                            ""Country"" VARCHAR2(100) DEFAULT 'India' NOT NULL,
                            ""Phone"" VARCHAR2(20),
                            ""Email"" VARCHAR2(256),
                            ""Website"" VARCHAR2(500),
                            ""GstIn"" VARCHAR2(50),
                            ""BusinessType"" VARCHAR2(100) DEFAULT 'General Retail Store' NOT NULL,
                            ""SellingModel"" VARCHAR2(50) DEFAULT 'GOODS_AND_SERVICES' NOT NULL,
                            ""GstScheme"" VARCHAR2(50) DEFAULT 'Regular' NOT NULL,
                            ""RegisteredState"" VARCHAR2(100),
                            ""CustomTerminologyJson"" NCLOB,
                            ""DefaultTaxRate"" NUMBER(5,2) DEFAULT 18.00 NOT NULL,
                            ""PricesIncludeTax"" NUMBER(1) DEFAULT 1 NOT NULL,
                            ""ReceiptHeader"" VARCHAR2(500),
                            ""ReceiptFooter"" VARCHAR2(500),
                            ""ShowLogoOnReceipt"" NUMBER(1) DEFAULT 1 NOT NULL,
                            ""ReceiptTemplateType"" VARCHAR2(50) DEFAULT 'Thermal80mm' NOT NULL,
                            ""IsSuspended"" NUMBER(1) DEFAULT 0 NOT NULL,
                            ""ActivePlanId"" NUMBER(10) DEFAULT 1 NOT NULL REFERENCES ""SubscriptionPlans""(""Id"") ON DELETE SET NULL,
                            ""AllowedBranches"" NUMBER(10) DEFAULT 1 NOT NULL,
                            ""AllowedStaff"" NUMBER(10) DEFAULT 2 NOT NULL,
                            ""RazorpayCustomerId"" VARCHAR2(100),
                            ""RazorpaySubscriptionId"" VARCHAR2(100),
                            ""SubscriptionStatus"" VARCHAR2(50) DEFAULT 'Inactive' NOT NULL,
                            ""SubscriptionExpiresAt"" TIMESTAMP,
                            ""CreatedAt"" TIMESTAMP NOT NULL,
                            ""UpdatedAt"" TIMESTAMP
                        )",

                        @"CREATE TABLE ""Branches"" (
                            ""Id"" NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                            ""BusinessId"" NUMBER(10) NOT NULL REFERENCES ""Businesses""(""Id"") ON DELETE CASCADE,
                            ""Name"" VARCHAR2(100) NOT NULL,
                            ""Address"" VARCHAR2(500),
                            ""City"" VARCHAR2(100),
                            ""PostalCode"" VARCHAR2(20),
                            ""Phone"" VARCHAR2(20),
                            ""IsActive"" NUMBER(1) DEFAULT 1 NOT NULL,
                            ""CreatedAt"" TIMESTAMP NOT NULL
                        )",

                        @"CREATE TABLE ""Categories"" (
                            ""Id"" NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                            ""BusinessId"" NUMBER(10) NOT NULL REFERENCES ""Businesses""(""Id"") ON DELETE CASCADE,
                            ""ParentId"" NUMBER(10) REFERENCES ""Categories""(""Id""),
                            ""Name"" VARCHAR2(100) NOT NULL,
                            ""Type"" VARCHAR2(50) DEFAULT 'Service' NOT NULL,
                            ""CreatedAt"" TIMESTAMP NOT NULL
                        )",

                        @"CREATE TABLE ""Customers"" (
                            ""Id"" NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                            ""BusinessId"" NUMBER(10) NOT NULL REFERENCES ""Businesses""(""Id"") ON DELETE CASCADE,
                            ""Name"" VARCHAR2(200) NOT NULL,
                            ""Phone"" VARCHAR2(20),
                            ""Email"" VARCHAR2(256),
                            ""GstIn"" VARCHAR2(50),
                            ""IsWalkIn"" NUMBER(1) DEFAULT 0 NOT NULL,
                            ""CreatedAt"" TIMESTAMP NOT NULL,
                            ""UpdatedAt"" TIMESTAMP
                        )",

                        @"CREATE TABLE ""Services"" (
                            ""Id"" NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                            ""BusinessId"" NUMBER(10) NOT NULL REFERENCES ""Businesses""(""Id"") ON DELETE CASCADE,
                            ""Name"" VARCHAR2(200) NOT NULL,
                            ""SKU"" VARCHAR2(50) NOT NULL,
                            ""Category"" VARCHAR2(100) NOT NULL,
                            ""BasePrice"" NUMBER(18,2) NOT NULL,
                            ""TaxRate"" NUMBER(5,2) DEFAULT 0 NOT NULL,
                            ""Status"" VARCHAR2(20) DEFAULT 'Active' NOT NULL,
                            ""ImageUrl"" VARCHAR2(500),
                            ""CreatedAt"" TIMESTAMP NOT NULL,
                            ""UpdatedAt"" TIMESTAMP
                        )",

                        @"CREATE TABLE ""InventoryItems"" (
                            ""Id"" NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                            ""BusinessId"" NUMBER(10) NOT NULL REFERENCES ""Businesses""(""Id"") ON DELETE CASCADE,
                            ""Name"" VARCHAR2(200) NOT NULL,
                            ""SKU"" VARCHAR2(50) NOT NULL,
                            ""Category"" VARCHAR2(100) NOT NULL,
                            ""CurrentStock"" NUMBER(10) DEFAULT 0 NOT NULL,
                            ""Unit"" VARCHAR2(50) DEFAULT 'pcs' NOT NULL,
                            ""ReorderLevel"" NUMBER(10) DEFAULT 5 NOT NULL,
                            ""ImageUrl"" VARCHAR2(500),
                            ""CreatedAt"" TIMESTAMP NOT NULL,
                            ""UpdatedAt"" TIMESTAMP
                        )",

                        @"CREATE TABLE ""StaffMembers"" (
                            ""Id"" NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                            ""BusinessId"" NUMBER(10) NOT NULL REFERENCES ""Businesses""(""Id"") ON DELETE CASCADE,
                            ""UserId"" NUMBER(10) REFERENCES ""Users""(""Id"") ON DELETE SET NULL,
                            ""BranchId"" NUMBER(10) REFERENCES ""Branches""(""Id"") ON DELETE SET NULL,
                            ""Name"" VARCHAR2(200) NOT NULL,
                            ""EmpCode"" VARCHAR2(50) NOT NULL,
                            ""Contact"" VARCHAR2(256),
                            ""Role"" VARCHAR2(50) DEFAULT 'Staff' NOT NULL,
                            ""TotalBills"" NUMBER(10) DEFAULT 0 NOT NULL,
                            ""RevenueGenerated"" NUMBER(18,2) DEFAULT 0 NOT NULL,
                            ""Status"" VARCHAR2(20) DEFAULT 'Active' NOT NULL,
                            ""CreatedAt"" TIMESTAMP NOT NULL,
                            ""UpdatedAt"" TIMESTAMP
                        )",

                        @"CREATE TABLE ""Bills"" (
                            ""Id"" NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                            ""BusinessId"" NUMBER(10) NOT NULL REFERENCES ""Businesses""(""Id"") ON DELETE CASCADE,
                            ""BranchId"" NUMBER(10) NOT NULL REFERENCES ""Branches""(""Id""),
                            ""CustomerId"" NUMBER(10) NOT NULL REFERENCES ""Customers""(""Id""),
                            ""CreatedByStaffId"" NUMBER(10) REFERENCES ""StaffMembers""(""Id"") ON DELETE SET NULL,
                            ""BillNumber"" VARCHAR2(50) NOT NULL,
                            ""Subtotal"" NUMBER(18,2) NOT NULL,
                            ""DiscountCode"" VARCHAR2(50),
                            ""DiscountAmount"" NUMBER(18,2) DEFAULT 0 NOT NULL,
                            ""TaxAmount"" NUMBER(18,2) DEFAULT 0 NOT NULL,
                            ""TotalAmount"" NUMBER(18,2) NOT NULL,
                            ""PaymentMethod"" VARCHAR2(20) DEFAULT 'Cash' NOT NULL,
                            ""Status"" VARCHAR2(20) DEFAULT 'Pending' NOT NULL,
                            ""InvoicePdfUrl"" VARCHAR2(500),
                            ""IdempotencyKey"" VARCHAR2(100),
                            ""PaymentReference"" VARCHAR2(200),
                            ""Notes"" VARCHAR2(500),
                            ""CreatedAt"" TIMESTAMP NOT NULL,
                            ""UpdatedAt"" TIMESTAMP
                        )",

                        @"CREATE TABLE ""BillItems"" (
                            ""Id"" NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                            ""BillId"" NUMBER(10) NOT NULL REFERENCES ""Bills""(""Id"") ON DELETE CASCADE,
                            ""ServiceId"" NUMBER(10) NOT NULL REFERENCES ""Services""(""Id""),
                            ""ServiceName"" VARCHAR2(200) NOT NULL,
                            ""UnitPrice"" NUMBER(18,2) NOT NULL,
                            ""Quantity"" NUMBER(10) DEFAULT 1 NOT NULL,
                            ""ItemType"" VARCHAR2(50) DEFAULT 'Service' NOT NULL,
                            ""LineTotal"" NUMBER(18,2) NOT NULL,
                            ""HSNCode"" VARCHAR2(20),
                            ""SACCode"" VARCHAR2(20),
                            ""TaxableValue"" NUMBER(18,2) DEFAULT 0 NOT NULL,
                            ""TaxRate"" NUMBER(5,2) DEFAULT 18.00 NOT NULL,
                            ""CGSTRate"" NUMBER(5,2) DEFAULT 9.00 NOT NULL,
                            ""CGSTAmount"" NUMBER(18,2) DEFAULT 0 NOT NULL,
                            ""SGSTRate"" NUMBER(5,2) DEFAULT 9.00 NOT NULL,
                            ""SGSTAmount"" NUMBER(18,2) DEFAULT 0 NOT NULL,
                            ""IGSTRate"" NUMBER(5,2) DEFAULT 0 NOT NULL,
                            ""IGSTAmount"" NUMBER(18,2) DEFAULT 0 NOT NULL,
                            ""CessRate"" NUMBER(5,2) DEFAULT 0 NOT NULL,
                            ""CessAmount"" NUMBER(18,2) DEFAULT 0 NOT NULL
                        )",

                        @"CREATE TABLE ""Expenses"" (
                            ""Id"" NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                            ""BusinessId"" NUMBER(10) NOT NULL REFERENCES ""Businesses""(""Id"") ON DELETE CASCADE,
                            ""Description"" VARCHAR2(500) NOT NULL,
                            ""Amount"" NUMBER(18,2) NOT NULL,
                            ""Category"" VARCHAR2(100) NOT NULL,
                            ""ExpenseDate"" TIMESTAMP NOT NULL,
                            ""CreatedAt"" TIMESTAMP NOT NULL
                        )",

                        @"CREATE TABLE ""Purchases"" (
                            ""Id"" NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                            ""BusinessId"" NUMBER(10) NOT NULL REFERENCES ""Businesses""(""Id"") ON DELETE CASCADE,
                            ""VendorName"" VARCHAR2(200) NOT NULL,
                            ""InvoiceNumber"" VARCHAR2(100),
                            ""Subtotal"" NUMBER(18,2) DEFAULT 0 NOT NULL,
                            ""TaxAmount"" NUMBER(18,2) DEFAULT 0 NOT NULL,
                            ""TotalAmount"" NUMBER(18,2) NOT NULL,
                            ""Status"" VARCHAR2(50) DEFAULT 'Paid' NOT NULL,
                            ""PurchaseDate"" TIMESTAMP NOT NULL,
                            ""CreatedAt"" TIMESTAMP NOT NULL
                        )",

                        @"CREATE TABLE ""PurchaseItems"" (
                            ""Id"" NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                            ""PurchaseId"" NUMBER(10) NOT NULL REFERENCES ""Purchases""(""Id"") ON DELETE CASCADE,
                            ""InventoryItemId"" NUMBER(10) REFERENCES ""InventoryItems""(""Id""),
                            ""ItemName"" VARCHAR2(200) NOT NULL,
                            ""UnitPrice"" NUMBER(18,2) NOT NULL,
                            ""Quantity"" NUMBER(10) DEFAULT 1 NOT NULL,
                            ""LineTotal"" NUMBER(18,2) NOT NULL
                        )",

                        @"CREATE TABLE ""WhatsAppAccounts"" (
                            ""Id"" NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                            ""BusinessId"" NUMBER(10) NOT NULL REFERENCES ""Businesses""(""Id"") ON DELETE CASCADE,
                            ""MetaBusinessId"" VARCHAR2(100),
                            ""WabaId"" VARCHAR2(100),
                            ""PhoneNumberId"" VARCHAR2(100),
                            ""DisplayPhoneNumber"" VARCHAR2(30),
                            ""AccessToken"" VARCHAR2(1000),
                            ""TokenExpiry"" TIMESTAMP,
                            ""Status"" VARCHAR2(20) DEFAULT 'Pending' NOT NULL,
                            ""ConnectedAt"" TIMESTAMP NOT NULL,
                            ""DisconnectedAt"" TIMESTAMP
                        )",

                        @"CREATE TABLE ""WhatsAppTemplates"" (
                            ""Id"" NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                            ""WhatsAppAccountId"" NUMBER(10) NOT NULL REFERENCES ""WhatsAppAccounts""(""Id"") ON DELETE CASCADE,
                            ""TemplateName"" VARCHAR2(100) NOT NULL,
                            ""Language"" VARCHAR2(20) DEFAULT 'en' NOT NULL,
                            ""Category"" VARCHAR2(30) DEFAULT 'UTILITY' NOT NULL,
                            ""BodyText"" VARCHAR2(2000),
                            ""Status"" VARCHAR2(30) DEFAULT 'PENDING' NOT NULL,
                            ""CreatedAt"" TIMESTAMP NOT NULL,
                            ""UpdatedAt"" TIMESTAMP
                        )",

                        @"CREATE TABLE ""MessageLogs"" (
                            ""Id"" NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                            ""WhatsAppAccountId"" NUMBER(10) NOT NULL REFERENCES ""WhatsAppAccounts""(""Id"") ON DELETE CASCADE,
                            ""BillId"" NUMBER(10) REFERENCES ""Bills""(""Id"") ON DELETE SET NULL,
                            ""RecipientPhone"" VARCHAR2(20) NOT NULL,
                            ""MessageType"" VARCHAR2(20) DEFAULT 'text' NOT NULL,
                            ""MetaMessageId"" VARCHAR2(200),
                            ""Status"" VARCHAR2(20) DEFAULT 'Queued' NOT NULL,
                            ""SentAt"" TIMESTAMP NOT NULL,
                            ""DeliveredAt"" TIMESTAMP,
                            ""ReadAt"" TIMESTAMP,
                            ""FailedReason"" VARCHAR2(500)
                        )",

                        @"CREATE TABLE ""UserRefreshTokens"" (
                            ""Id"" NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                            ""UserId"" NUMBER(10) NOT NULL REFERENCES ""Users""(""Id"") ON DELETE CASCADE,
                            ""Token"" VARCHAR2(500) NOT NULL UNIQUE,
                            ""ExpiryTime"" TIMESTAMP NOT NULL,
                            ""IsRevoked"" NUMBER(1) DEFAULT 0 NOT NULL,
                            ""CreatedAt"" TIMESTAMP NOT NULL
                        )",

                        @"CREATE TABLE ""PendingRegistrations"" (
                            ""Id"" NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                            ""Token"" VARCHAR2(100) NOT NULL UNIQUE,
                            ""Email"" VARCHAR2(256) NOT NULL,
                            ""Username"" VARCHAR2(100) NOT NULL,
                            ""PasswordHash"" RAW(2000) NOT NULL,
                            ""PasswordSalt"" RAW(2000) NOT NULL,
                            ""LegalName"" VARCHAR2(200) NOT NULL,
                            ""Phone"" VARCHAR2(20),
                            ""GstIn"" VARCHAR2(50),
                            ""Address"" VARCHAR2(500),
                            ""SelectedPlanId"" NUMBER(10) DEFAULT 1 NOT NULL,
                            ""RazorpayCustomerId"" VARCHAR2(100),
                            ""RazorpaySubscriptionId"" VARCHAR2(100),
                            ""Status"" VARCHAR2(50) DEFAULT 'PendingPayment' NOT NULL,
                            ""ReminderEmailSent"" NUMBER(1) DEFAULT 0 NOT NULL,
                            ""ReminderEmailSentAt"" TIMESTAMP,
                            ""CreatedAt"" TIMESTAMP NOT NULL,
                            ""ExpiresAt"" TIMESTAMP NOT NULL,
                            ""RawRegistrationData"" NCLOB
                        )",

                        @"CREATE TABLE ""PaymentTransactions"" (
                            ""Id"" NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                            ""BusinessId"" NUMBER(10) REFERENCES ""Businesses""(""Id""),
                            ""RazorpayPaymentId"" VARCHAR2(100),
                            ""RazorpayOrderId"" VARCHAR2(100),
                            ""RazorpaySubscriptionId"" VARCHAR2(100),
                            ""Amount"" NUMBER(18,2) NOT NULL,
                            ""Status"" VARCHAR2(50) NOT NULL,
                            ""PaymentMethod"" VARCHAR2(50),
                            ""RawWebhookPayload"" NCLOB,
                            ""FailureReason"" VARCHAR2(500),
                            ""RetryCount"" NUMBER(10) DEFAULT 0 NOT NULL,
                            ""WebhookEventId"" NUMBER(10),
                            ""CorrelationId"" VARCHAR2(100),
                            ""CreatedAt"" TIMESTAMP NOT NULL,
                            ""UpdatedAt"" TIMESTAMP
                        )",

                        @"CREATE TABLE ""AuditLogs"" (
                            ""Id"" NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                            ""BusinessId"" NUMBER(10),
                            ""EntityType"" VARCHAR2(50) NOT NULL,
                            ""EntityId"" NUMBER(10),
                            ""Action"" VARCHAR2(50) NOT NULL,
                            ""OldValues"" NCLOB,
                            ""NewValues"" NCLOB,
                            ""PerformedBy"" VARCHAR2(100),
                            ""IpAddress"" VARCHAR2(50),
                            ""UserAgent"" VARCHAR2(500),
                            ""CorrelationId"" VARCHAR2(100),
                            ""Description"" VARCHAR2(1000),
                            ""CreatedAt"" TIMESTAMP NOT NULL
                        )",

                        @"CREATE TABLE ""WebhookEventLogs"" (
                            ""Id"" NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                            ""Source"" VARCHAR2(50) NOT NULL,
                            ""ExternalEventId"" VARCHAR2(200),
                            ""EventType"" VARCHAR2(100) NOT NULL,
                            ""RawPayload"" NCLOB,
                            ""ProcessingStatus"" VARCHAR2(30) DEFAULT 'Received' NOT NULL,
                            ""FailureReason"" VARCHAR2(2000),
                            ""RetryCount"" NUMBER(10) DEFAULT 0 NOT NULL,
                            ""CreatedAt"" TIMESTAMP NOT NULL,
                            ""ProcessedAt"" TIMESTAMP
                        )",

                        @"CREATE TABLE ""TaxCategories"" (
                            ""Id"" NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                            ""BusinessId"" NUMBER(10) REFERENCES ""Businesses""(""Id"") ON DELETE CASCADE,
                            ""Name"" VARCHAR2(100) NOT NULL,
                            ""TaxType"" VARCHAR2(20) DEFAULT 'Goods' NOT NULL,
                            ""HSNCode"" VARCHAR2(20),
                            ""SACCode"" VARCHAR2(20),
                            ""GSTPercentage"" NUMBER(5,2) DEFAULT 18.00 NOT NULL,
                            ""CGSTPercentage"" NUMBER(5,2) DEFAULT 9.00 NOT NULL,
                            ""SGSTPercentage"" NUMBER(5,2) DEFAULT 9.00 NOT NULL,
                            ""IGSTPercentage"" NUMBER(5,2) DEFAULT 18.00 NOT NULL,
                            ""CessPercentage"" NUMBER(5,2) DEFAULT 0.00 NOT NULL,
                            ""IsActive"" NUMBER(1) DEFAULT 1 NOT NULL,
                            ""CreatedAt"" TIMESTAMP NOT NULL
                        )",

                        @"CREATE TABLE ""HSNMasters"" (
                            ""Id"" NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                            ""Code"" VARCHAR2(20) NOT NULL,
                            ""Description"" VARCHAR2(500) NOT NULL,
                            ""SearchTerms"" VARCHAR2(500),
                            ""UQC"" VARCHAR2(20) DEFAULT 'PCS' NOT NULL,
                            ""DefaultGSTPercentage"" NUMBER(5,2) DEFAULT 18.00 NOT NULL,
                            ""IsActive"" NUMBER(1) DEFAULT 1 NOT NULL
                        )",

                        @"CREATE TABLE ""SACMasters"" (
                            ""Id"" NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                            ""Code"" VARCHAR2(20) NOT NULL,
                            ""Description"" VARCHAR2(500) NOT NULL,
                            ""SearchTerms"" VARCHAR2(500),
                            ""DefaultGSTPercentage"" NUMBER(5,2) DEFAULT 18.00 NOT NULL,
                            ""IsActive"" NUMBER(1) DEFAULT 1 NOT NULL
                        )",

                        @"CREATE TABLE ""BusinessTypeMasters"" (
                            ""Id"" NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                            ""Code"" VARCHAR2(100) NOT NULL,
                            ""Name"" VARCHAR2(150) NOT NULL,
                            ""Category"" VARCHAR2(100) NOT NULL,
                            ""IconName"" VARCHAR2(50) DEFAULT 'Store' NOT NULL,
                            ""SellingModel"" VARCHAR2(50) DEFAULT 'GOODS_AND_SERVICES' NOT NULL,
                            ""AliasesJson"" NCLOB,
                            ""DefaultFeaturesJson"" NCLOB,
                            ""DefaultTerminologyJson"" NCLOB,
                            ""IsActive"" NUMBER(1) DEFAULT 1 NOT NULL,
                            ""CreatedAt"" TIMESTAMP NOT NULL
                        )"
                    };

                    foreach (var sql in createTableSqls)
                    {
                        context.Database.ExecuteSqlRaw(sql);
                    }
                    Console.WriteLine("✓ 26 Oracle tables created cleanly matching all Entity models.");

                    // Create uppercase synonyms so unquoted SQL queries work in SQL Developer
                    context.Database.ExecuteSqlRaw(@"
                        BEGIN
                            FOR t IN (SELECT table_name FROM user_tables) LOOP
                                IF UPPER(t.table_name) != t.table_name THEN
                                    BEGIN
                                        EXECUTE IMMEDIATE 'CREATE OR REPLACE SYNONYM ' || UPPER(t.table_name) || ' FOR ' || CHR(34) || t.table_name || CHR(34);
                                    EXCEPTION WHEN OTHERS THEN NULL;
                                    END;
                                END IF;
                            END LOOP;
                        END;");
                    Console.WriteLine("✓ Created Oracle uppercase synonyms for unquoted SQL Developer queries.");

                    Console.WriteLine("\n[3/3] Seeding baseline Master Data & Subscription Plans...");
                    context.Database.ExecuteSqlRaw(@"
                        INSERT INTO ""SubscriptionPlans"" (""Name"", ""RazorpayPlanIdMonthly"", ""RazorpayPlanIdYearly"", ""MonthlyPrice"", ""YearlyPrice"", ""MaxBranches"", ""MaxStaff"", ""IsActive"") 
                        VALUES ('Starter Plan', 'plan_starter_m', 'plan_starter_y', 499, 4990, 1, 2, 1)");

                    context.Database.ExecuteSqlRaw(@"
                        INSERT INTO ""SubscriptionPlans"" (""Name"", ""RazorpayPlanIdMonthly"", ""RazorpayPlanIdYearly"", ""MonthlyPrice"", ""YearlyPrice"", ""MaxBranches"", ""MaxStaff"", ""IsActive"") 
                        VALUES ('Growth Plan', 'plan_growth_m', 'plan_growth_y', 1499, 14990, 5, 10, 1)");

                    context.Database.ExecuteSqlRaw(@"
                        INSERT INTO ""SubscriptionPlans"" (""Name"", ""RazorpayPlanIdMonthly"", ""RazorpayPlanIdYearly"", ""MonthlyPrice"", ""YearlyPrice"", ""MaxBranches"", ""MaxStaff"", ""IsActive"") 
                        VALUES ('Enterprise Plan', 'plan_enterprise_m', 'plan_enterprise_y', 4999, 49990, 99, 999, 1)");

                    Console.WriteLine("✓ Subscription Plans seeded successfully.");

                    // Seed Tax Categories
                    context.Database.ExecuteSqlRaw(@"
                        INSERT INTO ""TaxCategories"" (""Name"", ""TaxType"", ""HSNCode"", ""SACCode"", ""GSTPercentage"", ""CGSTPercentage"", ""SGSTPercentage"", ""IGSTPercentage"", ""CessPercentage"", ""IsActive"", ""CreatedAt"")
                        VALUES ('Standard Goods (18%)', 'Goods', '9999', NULL, 18.00, 9.00, 9.00, 18.00, 0.00, 1, CURRENT_TIMESTAMP)");
                    context.Database.ExecuteSqlRaw(@"
                        INSERT INTO ""TaxCategories"" (""Name"", ""TaxType"", ""HSNCode"", ""SACCode"", ""GSTPercentage"", ""CGSTPercentage"", ""SGSTPercentage"", ""IGSTPercentage"", ""CessPercentage"", ""IsActive"", ""CreatedAt"")
                        VALUES ('Reduced Goods (5%)', 'Goods', '1001', NULL, 5.00, 2.50, 2.50, 5.00, 0.00, 1, CURRENT_TIMESTAMP)");
                    context.Database.ExecuteSqlRaw(@"
                        INSERT INTO ""TaxCategories"" (""Name"", ""TaxType"", ""HSNCode"", ""SACCode"", ""GSTPercentage"", ""CGSTPercentage"", ""SGSTPercentage"", ""IGSTPercentage"", ""CessPercentage"", ""IsActive"", ""CreatedAt"")
                        VALUES ('Essential / Exempt (0%)', 'Goods', '0000', NULL, 0.00, 0.00, 0.00, 0.00, 0.00, 1, CURRENT_TIMESTAMP)");
                    context.Database.ExecuteSqlRaw(@"
                        INSERT INTO ""TaxCategories"" (""Name"", ""TaxType"", ""HSNCode"", ""SACCode"", ""GSTPercentage"", ""CGSTPercentage"", ""SGSTPercentage"", ""IGSTPercentage"", ""CessPercentage"", ""IsActive"", ""CreatedAt"")
                        VALUES ('Luxury Goods (28% + Cess)', 'Goods', '8703', NULL, 28.00, 14.00, 14.00, 28.00, 12.00, 1, CURRENT_TIMESTAMP)");
                    context.Database.ExecuteSqlRaw(@"
                        INSERT INTO ""TaxCategories"" (""Name"", ""TaxType"", ""HSNCode"", ""SACCode"", ""GSTPercentage"", ""CGSTPercentage"", ""SGSTPercentage"", ""IGSTPercentage"", ""CessPercentage"", ""IsActive"", ""CreatedAt"")
                        VALUES ('Restaurant Service (5%)', 'Services', NULL, '996331', 5.00, 2.50, 2.50, 5.00, 0.00, 1, CURRENT_TIMESTAMP)");
                    context.Database.ExecuteSqlRaw(@"
                        INSERT INTO ""TaxCategories"" (""Name"", ""TaxType"", ""HSNCode"", ""SACCode"", ""GSTPercentage"", ""CGSTPercentage"", ""SGSTPercentage"", ""IGSTPercentage"", ""CessPercentage"", ""IsActive"", ""CreatedAt"")
                        VALUES ('IT & Professional Services (18%)', 'Services', NULL, '998313', 18.00, 9.00, 9.00, 18.00, 0.00, 1, CURRENT_TIMESTAMP)");
                    context.Database.ExecuteSqlRaw(@"
                        INSERT INTO ""TaxCategories"" (""Name"", ""TaxType"", ""HSNCode"", ""SACCode"", ""GSTPercentage"", ""CGSTPercentage"", ""SGSTPercentage"", ""IGSTPercentage"", ""CessPercentage"", ""IsActive"", ""CreatedAt"")
                        VALUES ('Personal Care / Salon (18%)', 'Services', NULL, '999721', 18.00, 9.00, 9.00, 18.00, 0.00, 1, CURRENT_TIMESTAMP)");

                    Console.WriteLine("✓ Tax Categories seeded successfully.");

                    // Seed Business Type Masters
                    context.Database.ExecuteSqlRaw(@"
                        INSERT INTO ""BusinessTypeMasters"" (""Code"", ""Name"", ""Category"", ""IconName"", ""SellingModel"", ""AliasesJson"", ""DefaultFeaturesJson"", ""DefaultTerminologyJson"", ""IsActive"", ""CreatedAt"")
                        VALUES ('restaurant', 'Restaurant', 'Food & Hospitality', 'Utensils', 'GOODS_AND_SERVICES', '[""hotel"",""dine in"",""eatery"",""food court"",""dhaba""]', '{{""products"":true,""services"":false,""inventory"":true,""appointments"":false,""customers"":true,""staff"":true,""khata"":true,""purchases"":true,""expenses"":true}}', '{{""product"":{{""singular"":""Menu Item"",""plural"":""Menu Items""}},""service"":{{""singular"":""Dining Service"",""plural"":""Dining Services""}},""customer"":{{""singular"":""Customer"",""plural"":""Customers""}},""invoice"":{{""singular"":""Order / Bill"",""plural"":""Orders / Bills""}},""inventory"":{{""singular"":""Ingredient Stock"",""plural"":""Ingredient Stock""}},""purchase"":{{""singular"":""Ingredient Purchase"",""plural"":""Ingredient Purchases""}},""supplier"":{{""singular"":""Vendor / Supplier"",""plural"":""Vendors & Suppliers""}},""staff"":{{""singular"":""Staff / Waiter"",""plural"":""Staff & Waiters""}}}}', 1, CURRENT_TIMESTAMP)");

                    context.Database.ExecuteSqlRaw(@"
                        INSERT INTO ""BusinessTypeMasters"" (""Code"", ""Name"", ""Category"", ""IconName"", ""SellingModel"", ""AliasesJson"", ""DefaultFeaturesJson"", ""DefaultTerminologyJson"", ""IsActive"", ""CreatedAt"")
                        VALUES ('tiffin_center', 'Tiffin Center / Mess', 'Food & Hospitality', 'Soup', 'GOODS_ONLY', '[""mess"",""tiffin"",""canteen"",""fast food"",""food stall"",""tiffin service""]', '{{""products"":true,""services"":false,""inventory"":false,""appointments"":false,""customers"":true,""staff"":false,""khata"":true,""purchases"":true,""expenses"":true}}', '{{""product"":{{""singular"":""Food Item"",""plural"":""Food Items""}},""customer"":{{""singular"":""Customer"",""plural"":""Customers""}},""invoice"":{{""singular"":""Bill"",""plural"":""Bills""}}}}', 1, CURRENT_TIMESTAMP)");

                    context.Database.ExecuteSqlRaw(@"
                        INSERT INTO ""BusinessTypeMasters"" (""Code"", ""Name"", ""Category"", ""IconName"", ""SellingModel"", ""AliasesJson"", ""DefaultFeaturesJson"", ""DefaultTerminologyJson"", ""IsActive"", ""CreatedAt"")
                        VALUES ('grocery_kirana', 'Grocery / Kirana Store', 'Retail', 'ShoppingCart', 'GOODS_ONLY', '[""kirana"",""grocery"",""provision store"",""super market"",""general store"",""departmental store""]', '{{""products"":true,""services"":false,""inventory"":true,""appointments"":false,""customers"":true,""staff"":true,""khata"":true,""purchases"":true,""expenses"":true}}', '{{""product"":{{""singular"":""Product"",""plural"":""Products""}},""customer"":{{""singular"":""Customer"",""plural"":""Customers""}},""invoice"":{{""singular"":""Bill"",""plural"":""Bills""}},""inventory"":{{""singular"":""Stock"",""plural"":""Stock & Inventory""}}}}', 1, CURRENT_TIMESTAMP)");

                    context.Database.ExecuteSqlRaw(@"
                        INSERT INTO ""BusinessTypeMasters"" (""Code"", ""Name"", ""Category"", ""IconName"", ""SellingModel"", ""AliasesJson"", ""DefaultFeaturesJson"", ""DefaultTerminologyJson"", ""IsActive"", ""CreatedAt"")
                        VALUES ('general_retail', 'General Retail Store', 'Retail', 'Store', 'GOODS_AND_SERVICES', '[""general"",""other"",""retail"",""shop""]', '{{""products"":true,""services"":true,""inventory"":true,""appointments"":false,""customers"":true,""staff"":true,""khata"":true,""purchases"":true,""expenses"":true}}', '{{""product"":{{""singular"":""Product"",""plural"":""Products""}},""service"":{{""singular"":""Service"",""plural"":""Services""}},""customer"":{{""singular"":""Customer"",""plural"":""Customers""}},""invoice"":{{""singular"":""Bill / Invoice"",""plural"":""Bills & Invoices""}}}}', 1, CURRENT_TIMESTAMP)");

                    Console.WriteLine("✓ Business Type Masters seeded successfully.");

                    Console.WriteLine("\n[4/4] Verification: Checking existing tables in Oracle DB...");
                    using (var cmd = context.Database.GetDbConnection().CreateCommand())
                    {
                        if (cmd.Connection.State != System.Data.ConnectionState.Open)
                            cmd.Connection.Open();
                        cmd.CommandText = "SELECT table_name FROM user_tables ORDER BY table_name";
                        using (var reader = cmd.ExecuteReader())
                        {
                            int count = 0;
                            Console.WriteLine("Found the following tables in Oracle Database:");
                            while (reader.Read())
                            {
                                count++;
                                Console.WriteLine($"  {count}. {reader.GetString(0)}");
                            }
                            Console.WriteLine($"Total Tables Count in DB: {count}");
                        }
                    }

                    Console.WriteLine("\n==================================================");
                    Console.WriteLine("SUCCESS: Oracle Database schema & migration updated!");
                    Console.WriteLine("==================================================");
                }
                catch (Exception ex)
                {
                    Console.ForegroundColor = ConsoleColor.Red;
                    Console.WriteLine($"\n[ERROR] Migration failed: {ex.Message}");
                    Console.WriteLine(ex.StackTrace);
                    Console.ResetColor();
                }
            }
        }
    }
}
